---
- name: Set the current timezone
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: timezone_changed

- name: Update the timezone
  when: timezone_changed|succeeded
  command: dpkg-reconfigure --frontend noninteractive tzdata
